version: "3.7"
services:

  ballotnav:
    volumes:
      - .:/ballotnav
      - /ballotnav/node_modules
    build: "./"
    image: "api"
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - NODE_ENV=development
      - DISABLE_DB_MIGRATION_AUTO_RUN
      - TOKEN_SECRET=verysecretstring
      - TOKEN_EXPIRY=86400
    depends_on:
      - db
    command: npm run dev

  db:
    image: jred/postgres:11-postgis
    restart: always
    environment:
      POSTGRES_USER: ballotnav
      POSTGRES_DB: main
      POSTGRES_PASSWORD: pgpass
    ports:
      # expose local postgres container on localhost:5434
      - "5434:5432"
