# build and push a docker image from the latest push to "develop" branch
on:
  push:
    branches:
      - main
      - master
      - develop
      - ci
    pull_request:
      - open
      - synchronized
jobs:
  backend:
    runs-on: ubuntu-latest
    name: build & push image
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare docker tag
        id: prepare
        run: |
          SHA=${{ github.sha }}
          echo ::set-output name=sha::${SHA:0:8}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build-and-push-image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ballotnav/ballotnav:${{ steps.prepare.outputs.sha }}

      - name: built image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
